### ISSUE TITLE
Can't install npm package

### ISSUE THREAD

**Issue by niabb** [strongloop/strong-cluster-socket.io-store#16]
I get the following error:

npm ERR! Linux 3.13.0-55-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--unsafe-perm"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: strong-store-cluster@'>=1.0.0 <2.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.1.1","0.1.3"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by bajtos** [comment]
You are trying to install a version that does not exist yet. Please modify your dependency specifier to `~0.1.3`.
